### ISSUE TITLE
Show All Routes

### ISSUE THREAD

**Issue by natanfelles** [lonnieezell/vulcan#14] opened 2017-10-20 20:45 UTC

**Comment by lonnieezell** [comment] 2017-10-23 03:44
Typically a question or description to go along with the issue is helpful :)

**Comment by natanfelles** [comment] 2017-10-23 17:31
:)

Just something like Laravel artisan:

```
+--------+-----------+-------------------------------+----------------------+---------------------------------------------------------------+--------------+
| Domain | Method    | URI                           | Name                 | Action                                                        | Middleware   |
+--------+-----------+-------------------------------+----------------------+---------------------------------------------------------------+--------------+
|        | GET|HEAD  | /                             |                      | App\Http\Controllers\SiteController@index                     | web          |
|        | GET|HEAD  | _debugbar/assets/javascript   | debugbar.assets.js   | Barryvdh\Debugbar\Controllers\AssetController@js              |              |
|        | GET|HEAD  | _debugbar/assets/stylesheets  | debugbar.assets.css  | Barryvdh\Debugbar\Controllers\AssetController@css             |              |
|        | GET|HEAD  | _debugbar/clockwork/{id}      | debugbar.clockwork   | Barryvdh\Debugbar\Controllers\OpenHandlerController@clockwork |              |
|        | GET|HEAD  | _debugbar/open                | debugbar.openhandler | Barryvdh\Debugbar\Controllers\OpenHandlerController@handle    |              |
|        | GET|HEAD  | api/user                      |                      | Closure                                                       | api,auth:api |
|        | GET|HEAD  | categoria/{id}                |                      | App\Http\Controllers\SiteController@categoria                 | web          |
|        | GET|HEAD  | contato                       |                      | App\Http\Controllers\SiteController@contato                   | web          |
|        | GET|HEAD  | painel                        |                      | App\Http\Controllers\Painel\PainelController@index            | web          |
|        | POST      | painel/produto                | produto.store        | App\Http\Controllers\Painel\ProdutoController@store           | web          |
|        | GET|HEAD  | painel/produto                | produto.index        | App\Http\Controllers\Painel\ProdutoController@index           | web          |
|        | GET|HEAD  | painel/produto-teste          |                      | App\Http\Controllers\Painel\ProdutoController@testes          | web          |
|        | GET|HEAD  | painel/produto/create         | produto.create       | App\Http\Controllers\Painel\ProdutoController@create          | web          |
|        | PUT|PATCH | painel/produto/{produto}      | produto.update       | App\Http\Controllers\Painel\ProdutoController@update          | web          |
|        | GET|HEAD  | painel/produto/{produto}      | produto.show         | App\Http\Controllers\Painel\ProdutoController@show            | web          |
|        | DELETE    | painel/produto/{produto}      | produto.destroy      | App\Http\Controllers\Painel\ProdutoController@destroy         | web          |
|        | GET|HEAD  | painel/produto/{produto}/edit | produto.edit         | App\Http\Controllers\Painel\ProdutoController@edit            | web          |
+--------+-----------+-------------------------------+----------------------+---------------------------------------------------------------+--------------+

```

**Comment by lonnieezell** [comment] 2017-10-23 21:03
I thought maybe that's what you were talking about. :) I'm good with something like this.

**Comment by lonnieezell** [comment] 2018-07-18 13:13
This exists in CI4 core now. Closing

**Closed as completed by lonnieezell** 2018-07-18 13:13 UTC
